name: Emaad Ahmed Manzoor
description: Blog of Emaad Ahmed Manzoor
url: "http://www.eyeshalfclosed.com"

# Author info
author_name: Emaad Ahmed Manzoor
author_image_path: /images/author-image.jpeg

# External services
github_url: "https://github.com/emaadmanzoor"
twitter_url: "https://twitter.com/emaadmanzoor"
linkedin_url: "https://linkedin.com/in/emaadmanzoor"
feed_url: "http://feeds.feedburner.com/eyeshalfclosed"
email: "emaadmanzoor@gmail.com"

# Markdown rendering
kramdown:
  #  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
permalink: /blog/:year/:month/:day/:title/

# important since the site is compiled
# on Github's servers
timezone: America/New_York
